# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-15 20:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsequiemos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptgift',
            name='finish_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 15, 20, 17, 51, 456625)),
        ),
        migrations.AlterField(
            model_name='attemptgift',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 15, 20, 17, 51, 456572)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 15, 20, 17, 51, 459415)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 15, 20, 17, 51, 454805)),
        ),
        migrations.AlterField(
            model_name='post',
            name='finish_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 15, 20, 17, 51, 454855)),
        ),
        migrations.AlterField(
            model_name='postulations',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 15, 20, 17, 51, 457840)),
        ),
    ]
