# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obsequiemos', '0002_auto_20170627_0119'),
        ('obsequiemos', '0002_auto_20170815_2017'),
    ]

    operations = [
    ]
