# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsequiemos', '0004_auto_20170829_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptgift',
            name='finish_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 29, 8, 63475)),
        ),
        migrations.AlterField(
            model_name='attemptgift',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 29, 8, 63409)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 29, 8, 66747)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 29, 8, 61130)),
        ),
        migrations.AlterField(
            model_name='post',
            name='finish_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 29, 8, 61184)),
        ),
        migrations.AlterField(
            model_name='postulations',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 29, 8, 64872)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'media/profile_images'),
        ),
    ]
