# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 00:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsequiemos', '0007_auto_20170829_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptgift',
            name='finish_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 31, 1, 96251)),
        ),
        migrations.AlterField(
            model_name='attemptgift',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 31, 1, 96151)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 31, 1, 101878)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 31, 1, 92552)),
        ),
        migrations.AlterField(
            model_name='post',
            name='finish_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 31, 1, 92637)),
        ),
        migrations.AlterField(
            model_name='postulations',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 31, 1, 98456)),
        ),
    ]
