# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obsequiemos', '0010_auto_20170829_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptgift',
            name='finish_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 45, 25, 278413)),
        ),
        migrations.AlterField(
            model_name='attemptgift',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 45, 25, 278362)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 45, 25, 281232)),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, upload_to=b'post_pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 45, 25, 276601)),
        ),
        migrations.AlterField(
            model_name='post',
            name='finish_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 45, 25, 276651)),
        ),
        migrations.AlterField(
            model_name='postulations',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 0, 45, 25, 279631)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=b'profile_images'),
            preserve_default=False,
        ),
    ]
